name: Publish to itch.io

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: butler
    steps:
      - uses: actions/checkout@v4
      - uses: samiser/godot-builder/publish@main
        with:
          itch-target: samiser/test:html
          butler-api-key: ${{ secrets.BUTLER_API_KEY }}
